// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wusrmvnuwrodvrujtpne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1c3Jtdm51d3JvZHZydWp0cG5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODgyMDcsImV4cCI6MjA2ODk2NDIwN30.z1wxTfocUhVT9plXEhwwsPvKlB4CK63Vc84-HYU0NOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});